version: '3.8'

services:
  watchme-web:
    image: 754724220380.dkr.ecr.ap-southeast-2.amazonaws.com/watchme-web:latest
    container_name: watchme-web-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"  # localhostのみにバインド（Nginx経由でアクセス）
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      # データの永続化
      - ./data_accounts:/app/data_accounts
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - watchme-network

networks:
  watchme-network:
    driver: bridge